AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'Guardfile'
    - 'spec/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'app/inputs/**/*'

  TargetRubyVersion: 2.4

  # Enabled by default
  DisabledByDefault: false

  # Get CopNames for easier fix.
  DisplayCopNames: true

  # Related style guide URL. )
  DisplayStyleGuide: true

Rails:
  Enabled: true

Rails/HasAndBelongsToMany:
  Enabled: false
Rails/SkipsModelValidations:
  Enabled: false

Style/AsciiComments:
  Description: 'Use only ascii symbols in comments.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#english-comments'
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - spec/*

Metrics/LineLength:
  Enabled: true
  Max: 120

Metrics/AbcSize:
  Enabled: true
  Max: 20
