language: ruby
bundler_args: --without production
addons:
  postgresql: "9.6"
rvm:
  - 2.4
script:
  - bundle exec rake
before_install:
  - gem update --system
  - gem install bundler
  - gem update bundler
before_script:
  - bundle exec rails db:create db:migrate
notifications:
  email: false
