image: ruby:2.5.1

pipelines:
  default:
    - step:
        caches:
          - bundler
        script:
          - curl -sL https://deb.nodesource.com/setup_10.x | bash -
          - apt-get install -y nodejs
          - apt-get install -y postgresql-client
          - export DATABASE_URL=postgresql://test_user:test_user_password@localhost/zaitt-ror-test_test
          - bundle install --path vendor/bundle
          - bundle exec rails db:setup
          - bundle exec rails db:test:prepare
          - bundle install
          - bundle exec rake
        services:
          - postgres
          - redis

definitions:
  caches:
    bundler: vendor/bundle

  services:
    postgres:
      image: postgres
      environment:
        POSTGRES_DB: 'zaitt-ror-test_test'
        POSTGRES_USER: 'test_user'
        POSTGRES_PASSWORD: 'test_user_password'
    redis:
      image: redis
