default: &default
  adapter: postgresql
  encoding: unicode

test:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: <%= ENV['POSTGRES_DB'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
